---
layout: default
---



<h1>Ejercicios con Algoritmos de Ordenamiento</h1>


<div align="center">
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT80aoB0F1j-BIij97MMvrSJp8hiiM5BiR1LQ&usqp=CAU">
</div>


<ul>

  <li><a href="https://github.com/BYRONTOSH/Ordenamiento/tree/burbuja" target="_blank">Burbuja</a></li>
  
</ul>



<hr>


<h1>Ejercicios con Algoritmos de Búsqueda</h1>

<div align="center">
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT80aoB0F1j-BIij97MMvrSJp8hiiM5BiR1LQ&usqp=CAU">
</div>


<ol>

  <li><a href="https://github.com/BYRONTOSH/Ordenamiento/tree/burbuja" target="_blank">Burbuja</a></li>
  
</ol>
